### ISSUE TITLE
Nodal attributes do not display on network plot on hover

### ISSUE THREAD

**Issue by martinamorris** [statnet/statnetWeb#77]
can be reproduced using built-in net faux.mesa.high

**Comment by netterie** [comment]
## Jeanette's replication of the problem

- Installed R 4.0.2
- Installed following packages using **CRAN**: shiny, ergm, sna, RColorBrewer, latticeExtra
- Set working directory to ```statnetWeb/inst/shiny/statnetWeb```
- Launched with shiny::runApp()
- In the Network Descriptives tab, an Interactive plot of faux.mesa.high makes the nodes BIGGER on hover but attribute name is not displayed:

![image](https://user-images.githubusercontent.com/4825649/88464328-96cd9000-ce6e-11ea-9e20-36544b3f59b8.png)

**Comment by martinamorris** [comment]
Interesting, I don't get the node enlargement using Windows. 

But I do get the warning/error in the console.

**Comment by netterie** [comment]
After browsing the code for a super long time, I realized that [lines 1400 to 1418](https://github.com/statnet/statnetWeb/blob/master/inst/shiny/statnetWeb/server.R#L1400:L1418) specifically code the attributes to display **UPON CLICK** only when **Interactive Plot** is selected. Indeed, this works!

![image](https://user-images.githubusercontent.com/4825649/88468643-68b27500-ce9b-11ea-9624-724859cde454.png)

Whether or not coordinates could or should display on hover rather than click:
- my low familiarity with this app and with network descriptives makes this a somewhat deeper question
- let me move on to #78 for now - it's related, and by the time I fix it I should be able to answer this question more quickly!

**Comment by martinamorris** [comment]
Ok then, thanks for that.  It works for me too when I select the interactive plot.

I didn't even notice that option, even though it was the very first choice up top...

> Whether or not coordinates could or should display on hover rather than click

If by "coordinates" you mean nodal attributes, then display on click is fine.  It might be helpful to come up some context specific help to let users know that when they switch to interactive plot that clicking the node brings up the attributes.  Will file a (not urgent) issue for this specifically.

**Comment by netterie** [comment]
Great, I see the new issue you've opened. Yes, by "coordinates" I did actually mean nodal attributes!
